version: "3.9"

services:
  db:
    image: postgres:16
    container_name: weather_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web_be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather_backend
    env_file:
      - ./.env       # .env in root rootu, contain DATABASE_URL a API_KEY
    environment:
      - RUNNING_IN_DOCKER=1
    depends_on:
      - db
    ports:
      - "5500:5500"

  web_fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather_frontend
    ports:
      - "8080:80"     # FE run inside the container on port 80
    depends_on:
      - web_be

volumes:
  postgres_data: