apiVersion: v1
kind: Service
metadata:
  name: weather-frontend
spec:
  type: NodePort
  selector:
    app: weather-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # pro přístup přes localhost:30080