version: '3.8'
services:
  db:
    image: postgres:16
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: pomelo
      POSTGRES_PASSWORD: pomeloheslo
      POSTGRES_DB: weather_app
    ports:
      - "5432:5432"
  
  web_be:
    build: .
    environment:
      DATABASE_URL: postgresql://pomelo:pomeloheslo@db:5432/weather_app
    depends_on:
      - db
    ports:
      - "8000:8000"